[env]
TERM = "xterm-256color"

[font]
size = 10.0

[font.bold]
family = "SauceCodePro Nerd Font"

[font.bold_italic]
family = "SauceCodePro Nerd Font"

[font.italic]
family = "SauceCodePro Nerd Font"

[font.normal]
family = "SauceCodePro Nerd Font"
style = "Regular"

[window]
decorations = "none"
opacity = 0.9
startup_mode = "Windowed"

[window.dimensions]
columns = 120
lines = 29
